Migrate + fixes to calculate padding and delayed draw fix to support …
doo/TouchImageView pull request #1
Opened 2017-08-29 07:46 UTC by lebedevsd1

…picasso

2017-08-29 11:10 UTC, Kubiria approved these changes

2017-08-30 11:51 UTC, ustav requested changes

2017-08-30 11:51 UTC, ustav commented on library/src/main/java/com/ortiz/touch/TouchImageView.java
> +        setMeasuredDimension(totalViewWidth, totalViewHeight);
revert this

2017-08-30 11:55 UTC, ustav approved these changes

2017-08-30 11:55 UTC, merged